version: "3.9"

services:
  api:
    build: .
    container_name: crud_livros_api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=livros_db
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - livros_network

  mongo:
    image: mongo:7.0
    container_name: crud_livros_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - livros_network

volumes:
  mongo_data:

networks:
  livros_network:
    driver: bridge
